version: "3"

services:
  db:
    image: mysql:8.0.33
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./db_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - symfony_app
  php:
    build:
      context: ./php
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ../:/var/www/symfony:cached
    networks:
      - symfony_app
  nginx:
    build:
      context: ./nginx
    volumes:
      - ../:/var/www/symfony:cached
    ports:
      - 8080:80
    networks:
      - symfony_app

networks:
  symfony_app: